// features svgicon imports
import searchIcon from "../assets/features/search-icon.svg";
import selectIcon from "../assets/features/select-icon.svg";
import standOutIcon from "../assets/features/stand-out-icon.svg";
// products svg imports
import privacyPolicy from "../assets/products/privacy-policy.svg";
import termsAndConditions from "../assets/products/terms-and-conditions.svg";
import domainName from "../assets/products/domain-name.svg";
import invoice from "../assets/products/invoice.svg";


// feature data

export const featuresData = [
    {
      id: 1,
      icon: searchIcon,
      label: "Search",
      description:
        "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.",
    },
    {
      id: 2,
      icon: selectIcon,
      label: "Select",
      description:
        "Choose from thousands of options generated by the slogan maker that fit your needs.",
    },
    {
      id: 3,
      icon: standOutIcon,
      label: "Stand out",
      description: "Congrats on your new slogan. It's time to win the world!",
    },
  ];
  

//   products data

  export const productsData = [
    {
      id: 1,
      img: privacyPolicy,
      label: "Privacy Policy Generator",
      description:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
  
    {
      id: 2,
      img: termsAndConditions,
      label: "Terms & Conditions Generator",
      description:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
  
    {
      id: 3,
      img: domainName,
      label: "Domain Name Generator",
      description:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
  
    {
      id: 4,
      img: invoice,
      label: "Invoice Generator",
      description:
        "Stock your store with 100s of products and start selling to customers in minutes, without the hassle of inventory or packaging.",
    },
  ];

//   slogans data

  export const slogansData = [
    {
      id: 1,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 2,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 3,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 4,
      slogan: "Review the facts cool is the best.",
    },
    {
      id: 5,
      slogan: "Review the facts cool is the best.",
    },
    {
      id: 6,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 7,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 8,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 9,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 10,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 11,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 12,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 13,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 14,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 15,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 16,
      slogan: "coziness building for tomorrow",
    },
    {
      id: 17,
      slogan: "There is no Sore it will Not Heal, No cool it will not Subdue.",
    },
    {
      id: 18,
      slogan: "coziness building for tomorrow",
    },
  ];
  